### ISSUE TITLE
Can we validate template using this Parser

### ISSUE THREAD

**Issue by salahatwa** [armano2/freemarker-parser#36]
are it's availabe to validate any freemaker string template to return true if it valid else return false

**Comment by armano2** [comment]
i did some fixes too this project some time ago, but i was not seeing much "live" and requests/usages than i didn't even release it, my goal was to use this parser as part of linting tool and prettier, but it seems that there is not to many ppl that could care about this, than i moved my focus on other os projects

**Comment by salahatwa** [comment]
it's really great project , thanks for your support bro ,
