### ISSUE TITLE
ESLint integration

### ISSUE THREAD

**Issue by JPeer264** [armano2/freemarker-parser#7]
Thanks for your awesome lib. Is this parser compatible with ESLint?
My goal is to get something like [this](https://github.com/evcohen/eslint-plugin-jsx-a11y). I think for that is an own plugin needed, right?

**Comment by armano2** [comment]
Wy goal was to build AST align with estree with ~same structure as eslint, but rules due to difference in types. There is no scope analysis and visitor keys are not specified, but beside of that, it should work correctly.

**Comment by armano2** [comment]
just small info: this project is not finished, some of syntax is not going to be parsed https://github.com/armano2/freemarker-parser/projects/1

**Comment by JPeer264** [comment]
Alright nice, thanks. I hope I'll find some time to start an freemarker eslint plugin ;) 

> just small info: this project is not finished

Thanks for the notice.
